---

- hosts: all
  roles:
  - role: makigas-setup
    become: true
    deploy_user: makigaseml
  - role: ANXS.postgresql
    become: true
    postgresql_version: 9.4
    postgresql_users:
    - name: makigas
      password: p4ssw0rd
    postgresql_user_privileges:
    - name: makigas
      role_attr_flags: "CREATEDB,LOGIN"
  - role: rvm_io.ruby
    become: true
    become_user: makigaseml
    rvm1_rubies: ['ruby-2.3.3']
    rvm1_user: makigaseml