---

- hosts: all
  roles:
  - role: makigas-setup
    become: true
    deploy_user: makigaseml
    deploy_group: operators
  - role: ANXS.postgresql
    become: true
    postgresql_version: 9.4
    postgresql_users:
    - name: makigas
      password: p4ssw0rd
    postgresql_user_privileges:
    - name: makigas
      role_attr_flags: "CREATEDB,LOGIN"
  - role: rvm_io.ruby
    become: true
    rvm1_rubies: ['ruby-2.3.3']
    rvm1_install_flags: '--auto-dotfiles'
    rvm1_install_path: '/usr/local/rvm'
    rvm1_user: root